language: node_js
node_js:
  - "4.2.6"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run build
  - git config --global user.email "lucky.zhou@xplusz.com"
  - git config --global user.name "LuckyZhou880808"
  - git config --global user.password "P@ssw0rd"
  - git add public/*
  - git commit -m "build release"
  - git push origin master
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: "107ad221-0b7b-4c7f-9eeb-40ea5915f057"