language: node_js
node_js:
  - "4.2.6"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run build
  - git config --global user.email "lucky.zhou@xplusz.com"
  - git config --global user.name "LuckyZhou880808"
  - git add -f public/*
  - git commit -m "build release"
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: "0432de36-a083-4be6-a920-8e8156203411"